name: deekweb
description: A strongly-typed HTTP library for Flutter.
version: 1.0.0
repository: https://github.com/DeekFit/DeekWeb

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: