name: deekweb
description: >-
  A strongly-typed HTTP library for Dart and Flutter. 

  Provides mechanisms to define classes with response parsing for REST requests.
version: 1.0.3
repository: https://github.com/DeekFit/DeekWeb
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
  uwp:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1