name: deekweb
description: >-
  A strongly-typed HTTP library for Dart and Flutter. 

  Provides mechanisms to define classes with response parsing for REST requests.
version: 1.0.6
repository: https://github.com/DeekFit/DeekWeb
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.2.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1