name: deekweb
description: >-
  A strongly-typed HTTP library for Dart and Flutter. 
  Provides mechanisms to define strongly-typed classes with response parsing for REST requests.
version: 1.0.1
repository: https://github.com/DeekFit/DeekWeb

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1